#+Title: Backups of IIIT-Hyderabad Base machines' containers
#+Author: VLEAD Systems Team
* Introduction
  Purpose of this document/project is to have backups of VLEAD servers
  from various locations.
  
  [[http://rsnapshot.org/][rnsnapshot tool]] is used for backups

  All our base machines are configured in [[http://www.techrepublic.com/blog/the-enterprise-cloud/raid-50-offers-a-balance-of-performance-storage-capacity-and-data-integrity/][RAID50]]
  
* Base1 Backup
  - Base1 machine IP address is =10.4.12.21=.
  - Configured rsnapshot ( backup tool) in linux like machines
  - rsnapshot server runs in various time intervals (e.g hourly.0,
    hourly.1.. daily.0,daily.1... weekly.0,weekly.1... monthly.0,monthly.1.. etc.).
  - Please check =/etc/rsnapshot.conf= file on base1 machine for what
    files are getting backed up and where these files are getting
    backed up.
  - Till today ( 2017/07/27 ), all files are getting backed up in
    =/mnt/das1/snapshots/=.
** Rsync backups from BASE1 to BASE2 machine.
   - BASE2 machine IP is =10.4.12.22=
   - As of now, base1 backups are getting saved in local machine in
     =/mnt/das1/snapshot= which is not very feasible solution in case
     of OS failure or Hard Disk Drive failures.
   - So, It is compulsory to save these backup files in Storage Area
     Network( i.e SAN). So that recovery of VLEAD servers from the
     these backups is easier.
   - Set a cronjob on base1 to save the backup files into
     =/mnt/san1/base1-backup/=.
     #+BEGIN_SRC 
     0 * * * *	/usr/bin/rsync -avrz /mnt/das1/snapshots/hourly.0 root@10.4.12.22:/mnt/san1/base1-backup/
     #+END_SRC
     
     The above cronjob is added in base1 machine in root account. It
     executes every hour and saves the backup file in base2 machine in
     =/mnt/san1/base1-backup/=
* BASE2 Backups
  As of today ( 27/07/2017), It dose not have anything to take backup.
  It has =/mnt/san1=. Which is having backups of previous base2
  backups in =/mnt/san1/backup-snapshots/= and now onwards base2
  backups are in =/mnt/san1/base1-backup/=.

  - As of today, the base2 machine has only CentOS-6.9 Operating
    System installed.

* BASE3 Backups
  - BASE3 machine is having some production containers
  - BASE3 machine IP is =10.4.12.23=
  - BASE3 machine configured with rnsapshot server
  - Please check =/etc/rsnapshot.conf= file on base3 machine for what
    files are getting backed up and where these files are getting
    backed up.
  - Till today ( 2017/07/27 ), all files are getting backed up in
    =/mnt/das1/backup-snapshots/=.
** Cronjobs on base3 for root
   #+BEGIN_EXAMPLE
   0 1,5,9,13,17,21 * * *       /usr/bin/rsnapshot hourly
   45 23 * * *       /usr/bin/rsnapshot daily
   30 22 * * 0       /usr/bin/rsnapshot weekly
   10 3 16 * *       /usr/bin/rsnapshot monthly
   5 11,15 * * * /usr/bin/tail /var/log/rsnapshot
   #+END_EXAMPLE
* BASE4
  - BASE4 machine is for Testing environment for VLEAD employees
  - It also has =/mnt/san1= storage to have backups. But as of today,
    there are no backups happening on base4 machine.
* How to restore from the backup files
  Please refer the file [[../projects/report-on-base2-down.org][restoring-steps.org]] for restoring VLEAD
  servers from backups.
