#+Title: Backups
#+Author: VLEAD Systems Team
* Introduction
  Purpose of this document/project is to have backups of VLEAD servers
  from various locations.
  
  [[http://rsnapshot.org/][rnsnapshot tool]] is used for backups

  All our base machines are configured in [[http://www.techrepublic.com/blog/the-enterprise-cloud/raid-50-offers-a-balance-of-performance-storage-capacity-and-data-integrity/][RAID50]]
  
* Base1 Backup
  - Base1 machine IP address is =10.4.12.21=.
  - Configured rsnapshot ( backup tool) in linux like machines
  - rsnapshot server runs in various time intervals (e.g hourly.0,
    hourly.1.. daily.0,daily.1... weekly.0,weekly.1... monthly.0,monthly.1.. etc.).
  - Please check =/etc/rsnapshot.conf= file on base1 machine for what
    files are getting backed up and where these files are getting
    backed up.
  - Till today ( 2017/07/27 ), all files are getting backed up in
    =/mnt/das1/snapshots/=.
** Rsync backups from BASE1 to BASE2 machine.
   - BASE2 machine IP is =10.4.12.22=
   - As of now, base1 backups are getting saved in local machine in
     =/mnt/das1/snapshot= which is not very feasible solution in case
     of OS failure or Hard Disk Drive failures.
   - So, It is compulsory to save these backup files in Storage Area
     Network( i.e SAN). So that recovery of VLEAD servers from the
     these backups is easier.
   - Set a cronjob on base1 to save the backup files into
     =/mnt/san1/base1-backup/=.
     #+BEGIN_SRC 
     0 * * * *	/usr/bin/rsync -avrz /mnt/das1/snapshots/hourly.0 root@10.4.12.22:/mnt/san1/base1-backup/
     #+END_SRC
     
     The above cronjob is added in base1 machine in root account. It
     executes every hour and saves the backup file in base2 machine in
     =/mnt/san1/base1-backup/=
* BASE2 Backups
  As of today ( 27/07/2017), It dose not have anything to take backup.
  It has =/mnt/san1=. Which is having backups of previous base2
  backups in =/mnt/san1/backup-snapshots/= and now onwards base2
  backups are in =/mnt/san1/base1-backup/=.

  - As of today, the base2 machine has only CentOS-6.9 Operating
    System installed.

* BASE3 Backups
  - BASE3 machine is having some production containers
  - BASE3 machine IP is =10.4.12.23=
  - BASE3 machine configured with rnsapshot server
  - Please check =/etc/rsnapshot.conf= file on base3 machine for what
    files are getting backed up and where these files are getting
    backed up.
  - Till today ( 2017/07/27 ), all files are getting backed up in
    =/mnt/das1/backup-snapshots/=.
** Cronjobs on base3 for root
   #+BEGIN_EXAMPLE
   0 1,5,9,13,17,21 * * *       /usr/bin/rsnapshot hourly
   45 23 * * *       /usr/bin/rsnapshot daily
   30 22 * * 0       /usr/bin/rsnapshot weekly
   10 3 16 * *       /usr/bin/rsnapshot monthly
   5 11,15 * * * /usr/bin/tail /var/log/rsnapshot
   #+END_EXAMPLE
* BASE4
  - BASE4 machine is for Testing environment for VLEAD employees
  - It also has =/mnt/san1= storage to have backups. But as of today,
    there are no backups happening on base4 machine.
* AWS-Backups-Production.
  - On AWS( Amazon Web Services ), various production servers are
    running. they are
    1. router 
    2. osse-server 
    3. public-dns
    4. Private-dns
    5. reverse proxy
    6. nagios
    7. rsnapshot
    8. Outreach portal ( outreach.vlabs.ac.in )
    9. analytics-server( stats.vlabs.ac.in )
    10. feedback.vlabs.ac.in

   
  All the above servers configuration files and databases from
  outreach-portal and feedback servers are backed up in
  rsnapshot-server. 

** Backup of Backup( rsnapshot) serever
   In rnsnapshot server has all back ups of production servers, so
   need to be backed up this server in IIIT-H infrastructure.
   
   + I have done following steps
     1. Added NAT rule in Router vm
	#+BEGIN_EXAMPLE
	#Forward incoming SSH connection on TCP port 2424 to rsnapshot server
	-A PREROUTING -d 10.100.1.1 -p tcp -m tcp --dport 2424 -j DNAT --to-destination 10.100.1.10:22
	#+END_EXAMPLE
	#+BEGIN_EXAMPLE
	service iptables restart
	#+END_EXAMPLE

     2. Update Security-Group on AWS router VM
	 Accept connections on tcp port number 2424	from
         196.12.53.130/32, 10.100.0.0/22	
     3. Added another Firewall rule in rsnapshot-server in
           =/etc/sysconfig/iptables=
	   #+BEGIN_EXAMPLE
	   #Allow incoming connections from http container on base on TCP port 22
	   -A INPUT -m state --state NEW -s 196.12.53.130 -p tcp -m tcp --dport 22 -j ACCEPT
	   #+END_EXAMPLE
	   #+BEGIN_EXAMPLE
	   service restart iptables
	   #+END_EXAMPLE

     4. From ssh-tunnel from shankar account.
	   #+BEGIN_EXAMPLE
	   /usr/bin/rsync -azvv -e "ssh -p 2424 -i /home/shankar/aa1.pem"  root@54.85.93.7:/.snapshots/hourly.0   /home/shankar/backup/aws-backup/ --exclude ads/ --exclude reverseproxy/awstats/ --exclude reverseproxy/var/
	   #+END_EXAMPLE
	In above command, excluding some of the files, because we
	will have the same files from =stats.vlabs.ac.in= in the
	backup
     5. ssh-tunnel automatically backed up into
           =/mnt/san1/backup_snapshots/=
     6. Added cronjob too in ssh-tunnel
	- =script.sh=
	#+BEGIN_EXAMPLE
	/usr/bin/rsync -azvv -e "ssh -p 2424 -i /home/shankar/aa1.pem"  root@54.85.93.7:/.snapshots/hourly.0   /home/shankar/backup/aws-backup/ --exclude ads/ --exclude reverseproxy/awstats/ --exclude reverseproxy/var/ > logs.txt 2>&1
	#+END_EXAMPLE
	- cron job added in crontab using =crontab -e=
	#+BEGIN_EXAMPLE
	0 23 * * * sh /home/shankar/backup/aws-backup/script.sh
	#+END_EXAMPLE
   
	
   - So we have backup of backup server ( production AWS-rsnapshot
     server) in ssh-tunnel in
     =/home/shankar/backup/aws-backup/=. Again, these backups are
     rsynced to
     =/mnt/san1/backup-snapshots/hourly.0/ssh-tunnel.virtual-labs.ac.in/vz/private/12169/home/shankar/backup/aws-backup/hourly.0/=

  
  



* How to restore from the backup files
  Please refer the file [[../projects/report-on-base2-down.org][restoring-steps.org]] for restoring VLEAD
  servers from backups.
