#!/bin/bash
# Fix modules.dep for iptables
#
# chkconfig: 2345 08 92
# description: Simple script that fixed modules.dep for iptables
#

### BEGIN INIT INFO
# Provides: modules_dep
# Required-Start: $local_fs
# Required-Stop: $local_fs
# Should-Start: 
# Should-Stop: 
# Default-Start: 
# Default-Stop: 
# Short-Description: Fix modules.dep for iptables
# Description: Simple script that fixed modules.dep for iptables
### END INIT INFO

# source function library
. /etc/init.d/functions

function start() {
        if [ ! -d "/lib/modules/`uname -r`" ]; then
                mkdir /lib/modules/`uname -r`
        fi
        depmod -a >/dev/null 2>&1
}

function stop() {
        if [ -d "/lib/modules/`uname -r`" ]; then
                rm -rf /lib/modules/`uname -r`
        fi
}

case "$1" in
  start)
        start
        RETVAL=0
        ;;
  stop)
        stop
        RETVAL=0
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  try-restart|status)
        RETVAL=0
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
        RETVAL=2
esac

exit $RETVAL
