#+Title: Base2 machine Configuration details
#+Author: VLEAD
#+Date: [2018-08-09 Thu]

* Introduction
  This document captures the configuration of Base2 machine
* BAse2 Configuration
  - Base2 machine :: IBM
  - RAM :: 32GB
  - Hard Disk Drive :: 104 GB
* Operating System
  - Ubuntu 16.04 LTS Server Operating system as it is stable.
* User account details
  User account details as follows:
  - User name :: vlead
  - Password :: 
* Partitions
  Following partitions are created.
  - / (root) :: 
		Separate partition for =/(root)=. This
                partition contains all OS related files and
                installed packages.

		=/= = =20 GB=

  - /var/lib/docker  ::
                       Separate partition for =/var=. Mostly this
                      partition contains docker.  =/var/lib/docker= = =84 GB=
* Setting up network interface
  - Add the following lines in =/etc/network/interfaces= file
  #+BEGIN_EXAMPLE
  auto enp11s0f0
  iface enp11s0f0 inet static
    address 10.4.12.22
    netmask 255.255.252.0
    broadcast 10.4.15.255
    gateway 10.4.12.1
    dns-nameservers 10.4.12.160 10.4.12.221
    dns-search virtual-labs.ac.in
  #+END_EXAMPLE
  - Restart netwokring
  #+BEGIN_EXAMPLE
  $ sudo service networking restart
  #+END_EXAMPLE
* Installation of Docker
  - Add the following GPG key for the official Docker repository to
    the system
  #+BEGIN_EXAMPLE
  $ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  #+END_EXAMPLE
  - Add the Docker repository to APT sources
  #+BEGIN_EXAMPLE
  $ sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  #+END_EXAMPLE
  - Update the package database with the Docker packages from the
    newly added repo
  #+BEGIN_EXAMPLE
  $ sudo apt-get update
  #+END_EXAMPLE
  - Install docker
  #+BEGIN_EXAMPLE
  $ sudo apt-get install -y docker-ce
  #+END_EXAMPLE
  - Check the status of docker
  #+BEGIN_EXAMPLE
  $ sudo systemctl status docker
  #+END_EXAMPLE
